#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd & 
picom & 
xrandr --auto --output DP-0 --mode 1920x1080 --rate 144.00 --primary --right-of HDMI-0 
feh --bg-fill --randomizer ~/wallpapers/* &
sudo ntpd -qg &
fcitx5 -d &
bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

## Launch Polybar
$HOME/.config/polybar/launch.sh --shapes
## BSPWM Asethetics
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# border colors
bspc config focused_border_color "#4d4ea9"
bspc config normal_border_color  "#8888bd"
bspc config active_border_color  "#4d4ea9"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
